batch_size: 2
iters: 100

train_dataset:
  type: Cityscapes
  dataset_root: /root/paddlejob/workspace/train_data/datasets/cityscapes/
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: /root/paddlejob/workspace/train_data/datasets/cityscapes/
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0001
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
