_base_: '../_base_/cityscapes.yml'

batch_size: 4
iters: 80000


model:
  type: EncNet
  backbone:
    type: ResNet101_vd
    output_stride: 8
    multi_grid: [ 1, 2, 4 ]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  num_classes: 19
  backbone_indices: [0, 1, 2, 3]
  align_corners: False

loss:
  types:
    - type: CrossEntropyLoss
    - type: Seloss
    - type: CrossEntropyLoss
  coef: [1, 0.2, 0.4]
